"""Cross-language signature parity.

Reuses the JS SDK's golden-signature fixtures (generated by PHP with the same
primitive the server uses). If these pass, the Python SDK builds byte-identical
signatures to the PHP server and the JS SDK.
"""

from __future__ import annotations

import json
import re
import unittest
from pathlib import Path

from paylink import PaylinkClient
from paylink._field_orders import (
    CARD_CHARGE,
    CARD_REVOKE,
    CARD_TOKENIZE,
    INVOICE_CREATE,
    PAYMENT_CHECK_STATUS,
    PAYMENT_REFUND,
    PAYMENT_REVERSE_AUTHORIZATION,
    PAYMENT_SETTLE,
    PAYMENT_VOID,
    RECURRING_CREATE,
)
from paylink._sign_request import build_signed_body
from paylink.signature import build_signature
from paylink.webhooks import Webhooks

FIXTURES = json.loads((Path(__file__).parent / "golden-signatures.json").read_text())

ENDPOINT_SPECS = {
    "INVOICE_CREATE": INVOICE_CREATE,
    "PAYMENT_VOID": PAYMENT_VOID,
    "PAYMENT_REFUND": PAYMENT_REFUND,
    "PAYMENT_SETTLE": PAYMENT_SETTLE,
    "PAYMENT_REVERSE_AUTHORIZATION": PAYMENT_REVERSE_AUTHORIZATION,
    "PAYMENT_CHECK_STATUS": PAYMENT_CHECK_STATUS,
    "VCC_CHARGE": None,  # resolved below to avoid an import cycle in the map literal
    "CARD_TOKENIZE": CARD_TOKENIZE,
    "CARD_CHARGE": CARD_CHARGE,
    "CARD_REVOKE": CARD_REVOKE,
    "RECURRING_CREATE": RECURRING_CREATE,
}


def _camel_to_snake(key: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", key).lower()


def _snake_params(camel_input: dict) -> dict:
    return {_camel_to_snake(k): v for k, v in camel_input.items()}


class GoldenSignatureTest(unittest.TestCase):
    def test_primitive_signature_matches_every_case(self) -> None:
        """build_signature over the canonical `values` reproduces `expected`."""
        for case in FIXTURES["cases"]:
            with self.subTest(case=case["name"]):
                hash_token = case.get("hashToken", FIXTURES["hashToken"])
                self.assertEqual(
                    build_signature(case["values"], hash_token),
                    case["expected"],
                )

    def test_structured_body_signature_matches(self) -> None:
        """build_signed_body reproduces the signature from structured input.

        This is what proves the field-order registry is correct: the SDK derives
        the same ordered values from a params object that the server does.
        """
        from paylink._field_orders import VCC_CHARGE

        specs = dict(ENDPOINT_SPECS, VCC_CHARGE=VCC_CHARGE)

        for case in FIXTURES["cases"]:
            spec = specs.get(case["endpoint"])
            if spec is None:
                continue

            with self.subTest(case=case["name"]):
                hash_token = case.get("hashToken", FIXTURES["hashToken"])
                body = build_signed_body(
                    spec, _snake_params(case["input"]), "pub_token", hash_token
                )
                self.assertEqual(body["signature"], case["expected"])
                self.assertEqual(body["token"], "pub_token")

    def test_mandate_action_signs_the_uid(self) -> None:
        case = next(c for c in FIXTURES["cases"] if c["endpoint"] == "RECURRING_MANDATE_ACTION")
        hash_token = case.get("hashToken", FIXTURES["hashToken"])
        self.assertEqual(
            build_signature([case["input"]["mandateId"]], hash_token),
            case["expected"],
        )

    def test_webhook_signature_verifies(self) -> None:
        """Every webhook fixture verifies end-to-end via the public API."""
        for case in (c for c in FIXTURES["cases"] if c["endpoint"] == "WEBHOOK"):
            with self.subTest(case=case["name"]):
                hash_token = case.get("hashToken", FIXTURES["hashToken"])
                webhooks = Webhooks(
                    PaylinkClient(public_token="p", hash_token=hash_token)._config
                )
                payload = dict(case["input"], signature=case["expected"])
                event = webhooks.verify(payload)
                self.assertTrue(webhooks.is_valid(payload))
                self.assertEqual(event.raw["signature"], case["expected"])

                tampered = dict(payload, signature="AAAA")
                self.assertFalse(webhooks.is_valid(tampered))


if __name__ == "__main__":
    unittest.main()
